name = "github-file-manager"
main = "index.js"
compatibility_date = "2025-07-18"

# 环境变量配置
[[kv_namespaces]]
binding = "KV"
id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
preview_id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx